version: "3.8"

services:
    db:
        image: docker.io/library/postgres

        ports:
            - 5432:5432

        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: super_secret_password_maybe_you_should_change_this_but_thats_just_a_suggestion_you_dont_have_to

    app:
        build: .

        tty: true
        stdin_open: true

        # volumes:
        #     - .:/root/app
        depends_on:
            - "db"
