name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

defaults:
  run:
    shell: bash

jobs:
  # Style job
  lint:
    name: Check code quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Get cache dir of pip
        id: pip-cache
        run: |
          # `pip cache dir` was introduced in version 20.1
          python -m pip install 'pip>=20.1'
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade -r requirements-dev.txt

      - name: Install snadra
        run: |
          python -m pip install --editable .

      - name: Linting
        run: |
          ci/code_check.sh lint
        if: always()

      - name: Typing validation
        run: |
          ci/code_check.sh type
        if: always()

  # Test job
  test:
    name: Test ${{ matrix.python-version }} on ${{ matrix.os }}
    needs: [lint]

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python (${{ matrix.python-version }})
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get cache dir of pip
        id: pip-cache
        run: |
          # `pip cache dir` was introduced in version 20.1
          python -m pip install 'pip>=20.1'
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade -r requirements-dev.txt

      - name: Install snadra
        run: |
          python -m pip install --editable .

      - name: Running tests
        run: |
          ci/run_tests.sh
        if: always()

  # documentation job
  documentation:
    name: Test and build the documentation
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: false # Disabled for now


    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Get cache dir of pip
        id: pip-cache
        run: |
          # `pip cache dir` was introduced in version 20.1
          python -m pip install 'pip>=20.1'
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade -r requirements-dev.txt

      - name: Install snadra
        run: |
          python -m pip install --editable .

      - name: Doctest
        run: |
          ci/code_check.sh doctest

#      - name: Documentation build
#        run: |
#          ci/FOO_BAR.sh baz
