name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

defaults:
  run:
    shell: bash

env:
  HYPOTHESIS_PROFILE: CI
  SQLALCHEMY_WARN_20: 1

jobs:
  # Style job
  style:
    name: Style
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version:
          - 3.9
        os:
          - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3.1.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: |
          python -m pip install --upgrade wheel
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade pip

      - name: Get cache dir of pip
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: pip|${{ runner.os }}|${{ matrix.python-version }}|${{ hashFiles('setup.cfg') }}|${{ hashFiles('requirements-dev.txt') }}|${{ hashFiles('requirements/*.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade -r requirements/style.txt

      - name: Pip list
        run: |
          python -m pip list

      - name: Linting
        run: |
          ci/code_check.sh lint
        if: always()

      - name: Typing validation
        run: |
          ci/code_check.sh type
        if: always()

  # Test job
  test:
    name: Test ${{ matrix.python-version }} on ${{ matrix.os }}
    needs: [style]

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.8
          - 3.9
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3.1.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: |
          python -m pip install --upgrade wheel
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade pip

      - name: Get cache dir of pip
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: pip|${{ runner.os }}|${{ matrix.python-version }}|${{ hashFiles('setup.cfg') }}|${{ hashFiles('requirements-dev.txt') }}|${{ hashFiles('requirements/*.txt') }}

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade -r requirements/tests.txt

      - name: Install snadra
        run: |
          python -m pip install --upgrade --editable .

      - name: Pip list
        run: |
          python -m pip list

      - name: Running tests
        run: |
          pytest --tb=short tests/
        if: always()

  # documentation job
  documentation:
    name: Build documentation
    needs: [style, test]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version:
          - 3.9
        os:
          - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3.1.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install/Upgrade apt packages
        run: |
          sudo apt update
          sudo apt install --only-upgrade -y make

      - name: Update pip
        run: |
          python -m pip install --upgrade wheel
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade pip

      - name: Get cache dir of pip
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: pip|${{ runner.os }}|${{ matrix.python-version }}|${{ hashFiles('setup.cfg') }}|${{ hashFiles('requirements-dev.txt') }}|${{ hashFiles('requirements/*.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade -r requirements/docs.txt

      - name: Install snadra
        run: |
          python -m pip install --upgrade --editable .

      - name: Pip list
        run: |
          python -m pip list

      - name: Build documentation
        run: |
          cd docs/
          make clean
          sphinx-build -v -a -b html source/ build/html/

      - name: Upload documentation
        run: |
          echo "Just a placeholder for now:)"
